name: wake_on_lan
description: Send wake on LAN magic packets to devices on your local network.
version: 3.1.0+6
homepage: https://github.com/RoninComputer/package-wake-on-lan
repository: https://github.com/RoninComputer/package-wake-on-lan
issue_tracker: https://github.com/RoninComputer/package-wake-on-lan/issues
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  convert: ^3.0.1
dev_dependencies:
  lints: ^2.0.1
  test: ^1.20.1
scripts:
  netcat: nc -ul 9 | hexdump -C
