name: wake_on_lan
description: Send wake on LAN magic packets to devices on your local network.
version: 2.0.3
homepage: https://github.com/JagandeepBrar/wake_on_lan
repository: https://github.com/JagandeepBrar/wake_on_lan
issue_tracker: https://github.com/JagandeepBrar/wake_on_lan/issues
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  convert: ^3.0.1
dev_dependencies:
  test: ^1.20.1
scripts:
  netcat: nc -ul 9 | hexdump -C
